services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    build: ../backend/backend
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_dir:/app/staticfiles/
      - media_dir:/app/media/
      - ../data:/app/data
      - ../frontend/build/static:/app/frontend/build/static 
    env_file:
      - ../.env
    depends_on:
      - db

  frontend:
    build: ../frontend
    volumes:
      - ../frontend/build/static:/usr/share/nginx/html/static/

  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_dir:
  media_dir: