USER_USERNAME_MAX_LENGTH = 256
USER_EMAIL_MAX_LENGTH = 254
INGREDIENT_NAME_MAX_LENGTH = 200
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64
RECIPE_NAME_MAX_LENGTH = 256
RECIPE_SHORT_CODE_MAX_LENGTH = 22
RECIPE_COOKING_TIME_MIN = 1
RECIPE_COOKING_TIME_MAX = 480
INGREDIENT_AMOUNT_MIN = 1
INGREDIENT_AMOUNT_MAX = 1000
FIRST_NAME_MAX_LENGTH=150
LAST_NAME_MAX_LENGTH=150
USERNAME_NAME_MAX_LENGTH=150

BASIC_PAGE_SIZE = 6
