# Generated by Django 4.2 on 2025-05-21 17:39

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.ManyToManyField(related_name='used_in_recipes', through='recipes.IngredientRecipes', to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(default=shortuuid.ShortUUID().uuid, max_length=15, unique=True, verbose_name='Короткий код'),
        ),
    ]
